# Generated by Django 4.2.1 on 2024-10-29 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePlayingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-US', 'English'), ('ja-JP', 'Japanese'), ('zh-CN', 'Chinese'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('de-DE', 'German'), ('ru-RU', 'Russian')], default='en-US', max_length=10, verbose_name='Conversation Language')),
                ('level', models.SmallIntegerField(choices=[('1', 'Beginner'), ('2', 'Advanced')], default='1', verbose_name='Level')),
                ('situation', models.CharField(max_length=100, verbose_name='Situation')),
                ('situation_en', models.CharField(blank=True, help_text='Directly used in GPT prompt. If left blank, it will be automatically translated from the situation field.', max_length=100, verbose_name='Situation (English)')),
                ('my_role', models.CharField(max_length=100, verbose_name='My Role')),
                ('my_role_en', models.CharField(blank=True, help_text='Directly used in GPT prompt. If left blank, it will be automatically translated from my_role field.', max_length=100, verbose_name='My Role (English)')),
                ('gpt_role', models.CharField(max_length=100, verbose_name='GPT Role')),
                ('gpt_role_en', models.CharField(blank=True, help_text='Directly used in GPT prompt. If left blank, it will be automatically translated from gpt_role field.', max_length=100, verbose_name='GPT Role (English)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
